import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:just_audio_background/just_audio_background.dart';

import 'core/theme/app_theme.dart';
import 'core/routing/app_router.dart';
import 'core/services/notification_service.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure`

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Holds GEMINI_API_KEY for Kitty AI — never commit the actual .env file;
  // see .env.example.
  await dotenv.load(fileName: '.env');

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Must be a top-level function registered before runApp — this is what
  // lets FCM wake the app in a background isolate to handle a push while
  // fully terminated.
  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);

  // Must run before runApp — registers the lock-screen / notification
  // media session that AudioService (soundscapes) attaches tracks to.
  await JustAudioBackground.init(
    androidNotificationChannelId: 'com.kittysleep.app.audio',
    androidNotificationChannelName: 'Kitty Sleep Soundscapes',
    androidNotificationOngoing: true,
    androidStopForegroundOnPause: true,
  );

  runApp(const ProviderScope(child: KittySleepApp()));
}

class KittySleepApp extends ConsumerWidget {
  const KittySleepApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);

    return MaterialApp.router(
      title: 'Kitty Sleep',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.dark,
      darkTheme: AppTheme.dark,
      themeMode: ThemeMode.dark,
      routerConfig: router,
    );
  }
}
